name = "auto-poster-trigger-worker"
main = "src/index.js"
compatibility_date = "2024-05-02"

# Run three times a day to check queue and post (03:30 UTC, 08:30 UTC, 13:30 UTC)
[triggers]
crons = [ "30 3 * * *", "30 8 * * *", "30 13 * * *" ]

[vars]
GITHUB_OWNER = "pr6thv3"
GITHUB_REPO = "auto-poster-cloud"
GITHUB_WORKFLOW_FILE = "generate-youtube-short.yml"
ENABLE_CRON = "false"
ALLOW_LIVE_CRON = "false"
ALLOW_PUBLIC_CRON = "false"